tip_config: !send_tip
  address: 0x2a2a2a2a2a2a2a2a2a2a2a2a2a2a2a2a2a2a2a2a2a2a2a2a2a2a2a2a2a2a2a2a
  kind: !const 42
tx_freshness_threshold:
  secs: 36000
  nanos: 0
tx_max_future_threshold:
  secs: 30
  nanos: 0
