# Documentation for all configuration options:
# https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:
  - package-ecosystem: "cargo"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "sunday"
    commit-message:
      prefix: "fix"
      prefix-development: "chore"
      include: "scope"
    groups:
      cargo-minor-and-patch-dependencies:
        update-types:
          - "minor"
          - "patch"
    ignore:
      - dependency-name: futures-timer
      - dependency-name: move-core-types
      - dependency-name: mysten-metrics
      - dependency-name: protobuf # TODO: remove after fixing WAL-458
      - dependency-name: sui
      - dependency-name: sui-*
      - dependency-name: telemetry-subscribers
      - dependency-name: test-cluster
      - dependency-name: tokio
      - dependency-name: typed-store

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
    commit-message:
      prefix: "chore"
      include: "scope"
    groups:
      github-actions-all:
        patterns: ["*"]
