[default]
out = ["Html", "Xml"]
packages = [
  "walrus-core",
  "walrus-e2e-tests",
  "walrus-sdk",
  "walrus-service",
  "walrus-storage-node-client",
  "walrus-sui",
  "walrus-upload-relay",
  "walrus-utils",
]
run-types = ["Lib", "Tests"]
skip-clean = true
# Use separate target directory to avoid interference with other builds.
target-dir = "target/tarpaulin"
# Increase timeout for longer-running tests to 5 minutes.
timeout = "5min"
# Don't include test and benchmark code in the coverage result.
exclude-files = [
  "crates/**/benches/**/*",
  "crates/**/test_utils/**/*",
  "crates/**/tests/**/*",
  "crates/walrus-e2e-tests/**/*",
  "crates/walrus-orchestrator/**/*",
  "crates/walrus-proc-macros/**/*",
  "crates/walrus-simtest/**/*",
  "crates/walrus-stress/**/*",
  "crates/walrus-test-utils/**/*",
]
# TODO(WAL-986): Add the following after end-to-end tests work with `cargo tarpaulin`.
# args = ["--include-ignored"]
