[default]
skip-clean = true
run-types = ["Bins", "Doctests", "Examples", "Lib", "Tests"]
out = ["Html", "Xml"]
# Use separate target directory to avoid interference with other builds.
target-dir = "target/tarpaulin"
# Increase timeout for longer-running tests to 3 minutes.
timeout = "3min"
# Don't include test and benchmark code in the coverage result.
exclude-files = [
  "crates/**/benches/**/*",
  "crates/**/tests/**/*",
  "crates/**/test_utils/**/*",
  "crates/walrus-orchestrator/**/*",
  "crates/walrus-test-utils/**/*",
]
# Include all tests, even longer integration tests.
args = ["--include-ignored"]
