[workspace]
resolver = "2"
members = ["crates/*"]

[profile.simulator]
inherits = "test"
debug = true
debug-assertions = true
overflow-checks = true
# opt-level 1 gives >5x speedup for simulator tests without slowing down build times very much.
opt-level = 1

[workspace.package]
version = "0.1.0"
authors = ["Mysten Labs <build@mystenlabs.com>"]
edition = "2021"
license = "Apache-2.0"

[workspace.dependencies]
anyhow = "1.0.86"
bcs = "0.1.6"
clap = { version = "4.5.9", features = ["derive"] }
fastcrypto = "0.1"
futures = "0.3.30"
futures-timer = "=3.0.2" # required for MSIM
mime = "0.3.17"
move-core-types = { git = "https://github.com/MystenLabs/sui", rev = "ebf6df9225d998c1bd5cd0f4d584dd7af4961a37" }
mysten-metrics = { git = "https://github.com/MystenLabs/sui", rev = "ebf6df9225d998c1bd5cd0f4d584dd7af4961a37" }
opentelemetry = "^0.23.0"
opentelemetry-otlp = "^0.16"
opentelemetry_sdk = "^0.23.0"
prometheus = "0.13.4"
rand = "0.8.5"
reqwest = { version = "0.12.5", default-features = false, features = ["http2", "json", "rustls-tls"] }
rocksdb = "0.21.0"
serde = { version = "1.0.204", features = ["derive"] }
serde_json = "1.0.120"
serde_with = { version = "3.9", features = ["base64"] }
serde_yaml = "0.9"
# TODO(zhewu): Upgrade to 1.28 to use official sui release: https://github.com/MystenLabs/walrus/issues/569
sui-config = { git = "https://github.com/MystenLabs/sui", rev = "ebf6df9225d998c1bd5cd0f4d584dd7af4961a37" }
sui-framework = { git = "https://github.com/MystenLabs/sui", rev = "ebf6df9225d998c1bd5cd0f4d584dd7af4961a37" }
sui-keys = { git = "https://github.com/MystenLabs/sui", rev = "ebf6df9225d998c1bd5cd0f4d584dd7af4961a37" }
sui-macros = { git = "https://github.com/MystenLabs/sui", rev = "ebf6df9225d998c1bd5cd0f4d584dd7af4961a37" }
sui-move-build = { git = "https://github.com/MystenLabs/sui", rev = "ebf6df9225d998c1bd5cd0f4d584dd7af4961a37" }
sui-protocol-config = { git = "https://github.com/MystenLabs/sui", rev = "ebf6df9225d998c1bd5cd0f4d584dd7af4961a37" }
sui-sdk = { git = "https://github.com/MystenLabs/sui", rev = "ebf6df9225d998c1bd5cd0f4d584dd7af4961a37" }
sui-simulator = { git = "https://github.com/MystenLabs/sui", rev = "ebf6df9225d998c1bd5cd0f4d584dd7af4961a37" }
sui-types = { git = "https://github.com/MystenLabs/sui", rev = "ebf6df9225d998c1bd5cd0f4d584dd7af4961a37" }
telemetry-subscribers = { git = "https://github.com/MystenLabs/sui", rev = "ebf6df9225d998c1bd5cd0f4d584dd7af4961a37" }
tempfile = "3.10.1"
test-cluster = { git = "https://github.com/MystenLabs/sui", rev = "ebf6df9225d998c1bd5cd0f4d584dd7af4961a37" }
thiserror = "1.0.62"
tokio = "=1.36.0"
tokio-stream = "0.1.15"
tokio-util = "0.7.10"
tracing = "0.1.40"
tracing-opentelemetry = "0.24"
tracing-subscriber = "0.3.18"
typed-store = { git = "https://github.com/MystenLabs/sui", rev = "ebf6df9225d998c1bd5cd0f4d584dd7af4961a37" }
utoipa = { version = "4.2.3" }
walrus-core = { path = "crates/walrus-core" }
walrus-sdk = { path = "crates/walrus-sdk" }
walrus-service = { path = "crates/walrus-service" }
walrus-sui = { path = "crates/walrus-sui" }
walrus-test-utils = { path = "crates/walrus-test-utils" }

[workspace.lints.rust]
missing_docs = "warn"
missing_debug_implementations = "warn"
