[workspace]
resolver = "2"
members = ["crates/*"]

[workspace.package]
version = "0.1.0"
authors = ["Mysten Labs <build@mystenlabs.com>"]
edition = "2021"
license = "Apache-2.0"

[workspace.dependencies]
bcs = "0.1.6"
fastcrypto = "0.1"
move-core-types = { git = "https://github.com/MystenLabs/sui", tag = "testnet-v1.22.0" }
mysten-metrics = { git = "https://github.com/MystenLabs/sui", tag = "testnet-v1.22.0" }
rand = "0.8.5"
serde = { version = "1.0.197", features = ["derive"] }
serde_with = "3.7"
serde_yaml = "0.9"
sui-move-build = { git = "https://github.com/MystenLabs/sui", tag = "testnet-v1.22.0" }
sui-sdk = { git = "https://github.com/MystenLabs/sui", tag = "testnet-v1.22.0" }
sui-types = { git = "https://github.com/MystenLabs/sui", tag = "testnet-v1.22.0" }
telemetry-subscribers = { git = "https://github.com/MystenLabs/sui", tag = "testnet-v1.22.0" }
tempfile = "3.10.1"
test-cluster = { git = "https://github.com/MystenLabs/sui", tag = "testnet-v1.22.0" }
thiserror = "1.0.57"
tokio = { version = "1.37.0" }
tokio-stream = "0.1.14"
typed-store = { git = "https://github.com/MystenLabs/sui", tag = "testnet-v1.22.0" }
walrus-core = { path = "crates/walrus-core" }
walrus-sui = { path = "crates/walrus-sui" }
walrus-test-utils = { path = "crates/walrus-test-utils" }
clap = { version = "4.5.4", features = ["derive"] }
reqwest = { version = "0.12.3" }
futures = "0.3.30"

[workspace.lints.rust]
missing_docs = "warn"
missing_debug_implementations = "warn"
