[workspace]
resolver = "2"
members = ["crates/*"]

[workspace.package]
version = "0.1.0"
authors = ["Mysten Labs <build@mystenlabs.com>"]
edition = "2021"
license = "Apache-2.0"

[workspace.dependencies]
anyhow = "1.0.86"
async-trait = "0.1.81"
axum = { version = "0.7.5", features = ["http2"] }
base64 = "0.22.1"
bcs = "0.1.6"
clap = { version = "4.5.13", features = ["derive"] }
colored = "2.1.0"
criterion = "0.5.1"
enum_dispatch = "0.3"
fastcrypto = "0.1.8"
futures = "0.3.30"
futures-timer = "=3.0.2" # required for MSIM
git-version = "0.3.9"
home = "0.5.9"
humantime = "2.1.0"
indoc = "2.0.5"
itertools = "0.13.0"
mime = "0.3.17"
mockall = "0.12.1"
move-core-types = { git = "https://github.com/MystenLabs/sui", tag = "testnet-v1.30.1" }
mysten-metrics = { git = "https://github.com/MystenLabs/sui", tag = "testnet-v1.30.1" }
opentelemetry = "=0.23.0"
pin-project = "1.1.5"
prettytable = "0.10.0"
prometheus = "0.13.4"
quinn-proto = "0.11"
rand = "0.8.5"
raptorq = "2.0.0"
regex = "1"
reqwest = { version = "0.12.5", default-features = false, features = [
  "http2",
  "json",
  "rustls-tls",
] }
rocksdb = "0.21.0"
serde = { version = "1.0.204", features = ["derive"] }
serde_json = "1.0.122"
serde_test = "1.0.176"
serde_with = { version = "3.9", features = ["base64"] }
serde_yaml = "0.9"
sui-config = { git = "https://github.com/MystenLabs/sui", tag = "testnet-v1.30.1" }
sui-json-rpc-types = { git = "https://github.com/MystenLabs/sui", tag = "testnet-v1.30.1" }
sui-keys = { git = "https://github.com/MystenLabs/sui", tag = "testnet-v1.30.1" }
sui-macros = { git = "https://github.com/MystenLabs/sui", tag = "testnet-v1.30.1" }
sui-move-build = { git = "https://github.com/MystenLabs/sui", tag = "testnet-v1.30.1" }
sui-package-resolver = { git = "https://github.com/MystenLabs/sui", tag = "testnet-v1.30.1" }
sui-protocol-config = { git = "https://github.com/MystenLabs/sui", tag = "testnet-v1.30.1" }
sui-rest-api = { git = "https://github.com/MystenLabs/sui", tag = "testnet-v1.30.1" }
sui-sdk = { git = "https://github.com/MystenLabs/sui", tag = "testnet-v1.30.1" }
sui-simulator = { git = "https://github.com/MystenLabs/sui", tag = "testnet-v1.30.1" }
sui-storage = { git = "https://github.com/MystenLabs/sui", tag = "testnet-v1.30.1" }
sui-types = { git = "https://github.com/MystenLabs/sui", tag = "testnet-v1.30.1" }
telemetry-subscribers = { git = "https://github.com/MystenLabs/sui", tag = "testnet-v1.30.1" }
tempfile = "3.11.0"
test-cluster = { git = "https://github.com/MystenLabs/sui", tag = "testnet-v1.30.1" }
thiserror = "1.0.63"
tokio = "=1.36.0"
tokio-stream = "0.1.15"
tokio-util = "0.7.10"
tower-http = { version = "0.5.2", features = ["trace"] }
tracing = "0.1.40"
tracing-opentelemetry = "0.24"
tracing-subscriber = "0.3.18"
typed-store = { git = "https://github.com/MystenLabs/sui", tag = "testnet-v1.30.1" }
utoipa = { version = "4.2.3" }
utoipa-redoc = { version = "4.0.0", features = ["axum"] }
walrus-core = { path = "crates/walrus-core" }
walrus-event = { path = "crates/walrus-event" }
walrus-sdk = { path = "crates/walrus-sdk" }
walrus-service = { path = "crates/walrus-service" }
walrus-sui = { path = "crates/walrus-sui" }
walrus-test-utils = { path = "crates/walrus-test-utils" }

[workspace.lints.rust]
missing_docs = "warn"
missing_debug_implementations = "warn"

[profile.simulator]
inherits = "test"
debug = true
debug-assertions = true
overflow-checks = true
# opt-level 1 gives >5x speedup for simulator tests without slowing down build times very much.
opt-level = 1

[patch.crates-io]
quinn-proto = { git = "https://github.com/quinn-rs/quinn.git", rev = "f0fa66f871b80b9d2d7075d76967c649aecc0b77" }
