[workspace]
resolver = "2"
members = ["crates/*"]

[workspace.package]
version = "0.1.0"
authors = ["Mysten Labs <build@mystenlabs.com>"]
edition = "2021"
license = "Apache-2.0"

[workspace.dependencies]
bcs = "0.1.6"
fastcrypto = "0.1"
tempfile = "3.10.1"
thiserror = "1.0.57"
walrus-core = { path = "crates/walrus-core" }
walrus-test-utils = { path = "crates/walrus-test-utils" }
typed-store = { git = "https://github.com/MystenLabs/sui", tag = "testnet-v1.20.0" }

[workspace.lints.rust]
missing_docs = "warn"
