[workspace]
resolver = "2"
members = ["crates/*"]

[workspace.package]
version = "0.1.0"
authors = ["Mysten Labs <build@mystenlabs.com>"]
edition = "2021"
license = "Apache-2.0"

[workspace.dependencies]
anyhow = "1.0.82"
bcs = "0.1.6"
clap = { version = "4.5.4", features = ["derive"] }
fastcrypto = "0.1"
futures = "0.3.30"
move-core-types = { git = "https://github.com/MystenLabs/sui", tag = "testnet-v1.24.0" }
mysten-metrics = { git = "https://github.com/MystenLabs/sui", tag = "testnet-v1.24.0" }
rand = "0.8.5"
reqwest = "0.12.4"
serde = { version = "1.0.199", features = ["derive"] }
serde_json = "1.0.116"
serde_with = "3.8"
serde_yaml = "0.9"
sui-keys = { git = "https://github.com/MystenLabs/sui", tag = "testnet-v1.24.0" }
sui-move-build = { git = "https://github.com/MystenLabs/sui", tag = "testnet-v1.24.0" }
sui-sdk = { git = "https://github.com/MystenLabs/sui", tag = "testnet-v1.24.0" }
sui-types = { git = "https://github.com/MystenLabs/sui", tag = "testnet-v1.24.0" }
sui-config = { git = "https://github.com/MystenLabs/sui", tag = "testnet-v1.24.0" }
telemetry-subscribers = { git = "https://github.com/MystenLabs/sui", tag = "testnet-v1.24.0" }
tempfile = "3.10.1"
test-cluster = { git = "https://github.com/MystenLabs/sui", tag = "testnet-v1.24.0" }
thiserror = "1.0.59"
tokio = "1.37.0"
tokio-stream = "0.1.15"
tracing = "0.1.40"
tracing-subscriber = "0.3.18"
typed-store = { git = "https://github.com/MystenLabs/sui", tag = "testnet-v1.24.0" }
walrus-core = { path = "crates/walrus-core" }
walrus-sui = { path = "crates/walrus-sui" }
walrus-service = { path = "crates/walrus-service" }
walrus-test-utils = { path = "crates/walrus-test-utils" }
walrus-sdk = { path = "crates/walrus-sdk" }

[workspace.lints.rust]
missing_docs = "warn"
missing_debug_implementations = "warn"
