[workspace]
resolver = "2"
members = ["crates/*"]

[workspace.package]
version = "0.1.0"
authors = ["Mysten Labs <build@mystenlabs.com>"]
edition = "2021"
license = "Apache-2.0"

[workspace.dependencies]
anyhow = "1.0.86"
bcs = "0.1.6"
clap = { version = "4.5.8", features = ["derive"] }
fastcrypto = "0.1"
futures = "0.3.30"
mime = "0.3.17"
move-core-types = { git = "https://github.com/MystenLabs/sui", tag = "testnet-v1.27.2" }
mysten-metrics = { git = "https://github.com/MystenLabs/sui", tag = "testnet-v1.27.2" }
opentelemetry = "^0.23.0"
opentelemetry-otlp = "^0.16"
opentelemetry_sdk = "^0.23.0"
prometheus = "0.13.4"
rand = "0.8.5"
reqwest = { version = "0.12.5", default-features = false, features = ["http2", "json", "rustls-tls"] }
serde = { version = "1.0.203", features = ["derive"] }
serde_json = "1.0.119"
serde_with = { version = "3.8", features = ["base64"] }
serde_yaml = "0.9"
sui-config = { git = "https://github.com/MystenLabs/sui", tag = "testnet-v1.27.2" }
sui-keys = { git = "https://github.com/MystenLabs/sui", tag = "testnet-v1.27.2" }
sui-move-build = { git = "https://github.com/MystenLabs/sui", tag = "testnet-v1.27.2" }
sui-sdk = { git = "https://github.com/MystenLabs/sui", tag = "testnet-v1.27.2" }
sui-types = { git = "https://github.com/MystenLabs/sui", tag = "testnet-v1.27.2" }
telemetry-subscribers = { git = "https://github.com/MystenLabs/sui", tag = "testnet-v1.27.2" }
tempfile = "3.10.1"
test-cluster = { git = "https://github.com/MystenLabs/sui", tag = "testnet-v1.27.2" }
thiserror = "1.0.61"
tokio = "1.38.0"
tokio-stream = "0.1.15"
tracing = "0.1.40"
tracing-opentelemetry = "0.24"
tracing-subscriber = "0.3.18"
typed-store = { git = "https://github.com/MystenLabs/sui", tag = "testnet-v1.27.2" }
utoipa = { version = "4.2.3" }
walrus-core = { path = "crates/walrus-core" }
walrus-sdk = { path = "crates/walrus-sdk" }
walrus-service = { path = "crates/walrus-service" }
walrus-sui = { path = "crates/walrus-sui" }
walrus-test-utils = { path = "crates/walrus-test-utils" }

[workspace.lints.rust]
missing_docs = "warn"
missing_debug_implementations = "warn"
