[workspace]
resolver = "2"
members = ["crates/*"]

[workspace.package]
version = "1.0.0"
authors = ["Mysten Labs <build@mystenlabs.com>"]
edition = "2021"
license = "Apache-2.0"

[workspace.dependencies]
anyhow = "1.0.89"
async-trait = "0.1.83"
axum = { version = "0.7.7", default-features = false }
axum-server = { version = "0.7.1", default-features = false }
base64 = "0.22.1"
bcs = "0.1.6"
byteorder = "1.5.0"
chrono = "0.4"
clap = { version = "4.5.20", features = ["derive"] }
colored = "2.1.0"
criterion = "0.5.1"
enum_dispatch = "0.3"
fastcrypto = "0.1.8"
futures = { version = "0.3.31", default-features = false, features = ["async-await", "std"] }
futures-timer = "=3.0.2" # required for MSIM
futures-util = "0.3.30"
git-version = "0.3.9"
home = "0.5.9"
humantime = "2.1.0"
indoc = "2.0.5"
integer-encoding = "4.0.2"
itertools = "0.13.0"
mime = "0.3.17"
mockall = "0.12.1"
move-core-types = { git = "https://github.com/MystenLabs/sui", tag = "testnet-v1.35.0" }
mysten-metrics = { git = "https://github.com/MystenLabs/sui", tag = "testnet-v1.35.0" }
num-bigint = { version = "0.4.5", default-features = false }
opentelemetry = { version = "=0.25.0", default-features = false, features = ["trace"] }
p256 = "0.13.2"
pin-project = "1.1.6"
prettytable = "0.10.0"
prometheus = "0.13.4"
quote = "1.0"
rand = "0.8.5"
raptorq = "2.0.0"
rcgen = "0.13.1"
regex = "1"
reqwest = { version = "0.12.8", default-features = false, features = [ "http2", "json", "rustls-tls", ] }
rocksdb = "0.21.0"
rustls = { version = "0.23.14", default-features = false, features = ["ring", "tls12", "logging"] }
rustls-native-certs = "0.8.0"
serde = { version = "1.0.210", features = ["derive"] }
serde_json = "1.0.128"
serde_test = "1.0.177"
serde_with = { version = "3.11", features = ["base64"] }
serde_yaml = "0.9"
sui-config = { git = "https://github.com/MystenLabs/sui", tag = "testnet-v1.35.0" }
sui-json-rpc-types = { git = "https://github.com/MystenLabs/sui", tag = "testnet-v1.35.0" }
sui-keys = { git = "https://github.com/MystenLabs/sui", tag = "testnet-v1.35.0" }
sui-macros = { git = "https://github.com/MystenLabs/sui", tag = "testnet-v1.35.0" }
sui-move-build = { git = "https://github.com/MystenLabs/sui", tag = "testnet-v1.35.0" }
sui-package-resolver = { git = "https://github.com/MystenLabs/sui", tag = "testnet-v1.35.0" }
sui-protocol-config = { git = "https://github.com/MystenLabs/sui", tag = "testnet-v1.35.0" }
sui-rest-api = { git = "https://github.com/MystenLabs/sui", tag = "testnet-v1.35.0" }
sui-sdk = { git = "https://github.com/MystenLabs/sui", tag = "testnet-v1.35.0" }
sui-simulator = { git = "https://github.com/MystenLabs/sui", tag = "testnet-v1.35.0" }
sui-storage = { git = "https://github.com/MystenLabs/sui", tag = "testnet-v1.35.0" }
sui-types = { git = "https://github.com/MystenLabs/sui", tag = "testnet-v1.35.0" }
syn = "2.0"
telemetry-subscribers = { git = "https://github.com/MystenLabs/sui", tag = "testnet-v1.35.0" }
tempfile = "3.13.0"
test-cluster = { git = "https://github.com/MystenLabs/sui", tag = "testnet-v1.35.0" }
thiserror = "1.0.64"
tokio = "=1.38.1"
tokio-stream = "0.1.16"
tokio-util = "0.7.12"
tower = "0.5"
tower-http = { version = "0.5.2", features = ["trace"] }
tracing = "0.1.40"
tracing-opentelemetry = { version = "0.26", default-features = false }
tracing-subscriber = { version = "0.3.18", default-features = false }
typed-store = { git = "https://github.com/MystenLabs/sui", tag = "testnet-v1.35.0" }
url = "2.5.2"
utoipa = { version = "4.2.3" }
utoipa-redoc = { version = "4.0.0", features = ["axum"] }
walrus-core = { path = "crates/walrus-core" }
walrus-event = { path = "crates/walrus-event" }
walrus-proc-macros = { path = "crates/walrus-proc-macros" }
walrus-sdk = { path = "crates/walrus-sdk" }
walrus-service = { path = "crates/walrus-service" }
walrus-sui = { path = "crates/walrus-sui" }
walrus-test-utils = { path = "crates/walrus-test-utils" }
x509-cert = "0.2.5"

[workspace.lints.rust]
missing_docs = "warn"
missing_debug_implementations = "warn"
unexpected_cfgs = { level = "allow", check-cfg = ['cfg(msim)'] }

[profile.simulator]
inherits = "test"
debug = true
debug-assertions = true
overflow-checks = true
# opt-level 1 gives >5x speedup for simulator tests without slowing down build times very much.
opt-level = 1
