[workspace]
resolver = "2"
members = ["crates/*"]

[workspace.package]
version = "0.1.0"
authors = ["Mysten Labs <build@mystenlabs.com>"]
edition = "2021"
license = "Apache-2.0"

[workspace.dependencies]
bcs = "0.1.6"
fastcrypto = "0.1"
move-core-types = { git = "https://github.com/MystenLabs/sui", tag = "testnet-v1.20.0" }
mysten-metrics = { git = "https://github.com/MystenLabs/sui", tag = "testnet-v1.20.0" }
rand = "0.8.5"
serde = { version = "1.0.197", features = ["derive"] }
sui-move-build = { git = "https://github.com/MystenLabs/sui", tag = "testnet-v1.20.0" }
sui-sdk = { git = "https://github.com/MystenLabs/sui", tag = "testnet-v1.20.0" }
sui-types = { git = "https://github.com/MystenLabs/sui", tag = "testnet-v1.20.0" }
telemetry-subscribers = { git = "https://github.com/MystenLabs/sui", tag = "testnet-v1.20.0" }
tempfile = "3.10.1"
test-cluster = { git = "https://github.com/MystenLabs/sui", tag = "testnet-v1.20.0" }
thiserror = "1.0.57"
tokio = { version = "1.36.0" }
tokio-stream = "0.1.14"
typed-store = { git = "https://github.com/MystenLabs/sui", tag = "testnet-v1.20.0" }
walrus-core = { path = "crates/walrus-core" }
walrus-test-utils = { path = "crates/walrus-test-utils" }

[workspace.lints.rust]
missing_docs = "warn"
