# For documentation on how to configure this file,
# see https://diesel.rs/guides/configuring-diesel-cli

[print_schema.walrus-backup]
custom_type_derives = ["Clone", "diesel::query_builder::QueryId", "std::fmt::Debug"]
file = "crates/walrus-service/src/backup/schema.rs"

[migrations_directory]
dir = "crates/walrus-service/migrations"
