# Walrus S3 Gateway Configuration Example
# This file shows configuration options for the Walrus S3 Gateway with client-side signing

# Server settings
listen_address = "127.0.0.1:9200"

# Client-side signing configuration
[client_signing]
require_signatures = true
sui_rpc_url = "https://fullnode.testnet.sui.io:443"

# Walrus endpoints
[walrus]
publisher_url = "https://publisher.walrus-testnet.walrus.space"
aggregator_url = "https://aggregator.walrus-testnet.walrus.space"

# AWS S3 compatibility settings
[aws]
access_key_id = "your-access-key"
secret_access_key = "your-secret-key"
region = "us-east-1"

# Metadata storage
[metadata]
storage_type = "file"
storage_path = "./s3_metadata"

# Logging configuration
[logging]
level = "info"
