# Walrus S3 Gateway Configuration - Client-Side Signing
# This configuration enables secure Client-Side Signing for production use

[server]
# Address to bind the server to
bind_address = "0.0.0.0:8080"

# S3 region identifier (for S3 compatibility)
region = "us-east-1"

# TLS/HTTPS configuration
enable_tls = false
# tls_cert_path = "/path/to/certificate.pem"
# tls_key_path = "/path/to/private-key.pem"

# Request handling
request_timeout = 300  # seconds (5 minutes)
max_body_size = 67108864  # bytes (64 MB)
enable_cors = true

[client_signing]
# Whether to require transaction signatures for write operations
require_signatures = true

# Optional: Restrict operations to specific Sui addresses
# allowed_addresses = [
#   "0x1234567890abcdef1234567890abcdef12345678",
#   "0xabcdef1234567890abcdef1234567890abcdef12"
# ]

# Maximum transaction size in bytes
max_transaction_size = 1000000  # 1 MB

# Rate limiting per address (transactions per minute)
rate_limit_per_address = 100

# Whether to validate signature authenticity
validate_signatures = true

[walrus]
# Sui RPC endpoints (multiple for redundancy)
sui_rpc_urls = [
    "https://sui-testnet-rpc.mystenlabs.com:443",
    "https://sui-testnet.publicnode.com:443"
]

# Walrus storage node endpoints
storage_nodes = [
    "https://walrus-testnet.nodes.guru:11444",
    "https://walrus-testnet-storage.stakin-nodes.com:11444"
]

# How often to refresh committee information (seconds)
committee_refresh_interval = 300  # 5 minutes

# Request timeout for Walrus operations
request_timeout = 30  # seconds

# Metrics collection
enable_metrics = false
# metrics_port = 9090

# Client Credentials Configuration
# Each entry maps an S3 access key to a Sui address and permissions

[client_credentials.demo-client-1]
sui_address = "0x0000000000000000000000000000000000000000000000000000000000000000"
permissions = ["read", "write"]
description = "Demo client with read/write access"
active = true

[client_credentials.read-only-client]
sui_address = "0x1111111111111111111111111111111111111111111111111111111111111111"
permissions = ["read"]
description = "Read-only access client"
active = true

[client_credentials.admin-client]
sui_address = "0x2222222222222222222222222222222222222222222222222222222222222222"
permissions = ["read", "write", "delete", "create_bucket"]
description = "Administrative client with full access"
active = true

# Example: Disabled client
[client_credentials.disabled-client]
sui_address = "0x3333333333333333333333333333333333333333333333333333333333333333"
permissions = ["read"]
description = "Disabled client example"
active = false

# SECURITY NOTES:
# 
# 1. CLIENT-SIDE SIGNING SECURITY:
#    - Clients must sign all write operations locally
#    - Private keys never leave the client environment
#    - The gateway only validates signatures and submits transactions
#
# 2. PRODUCTION DEPLOYMENT:
#    - Always enable TLS in production (enable_tls = true)
#    - Use strong, unique access keys (not the demo keys above)
#    - Regularly rotate client credentials
#    - Monitor rate limits and adjust as needed
#    - Keep sui_rpc_urls and storage_nodes updated
#
# 3. ACCESS CONTROL:
#    - Configure 'allowed_addresses' to restrict Sui addresses
#    - Use minimal permissions for each client
#    - Disable unused credentials (active = false)
#    - Monitor transaction activity
#
# 4. OPERATIONAL SECURITY:
#    - Enable metrics for monitoring
#    - Set appropriate rate limits
#    - Use multiple RPC endpoints for redundancy
#    - Keep the gateway updated with latest security patches
