# Walrus S3 Gateway Configuration for Client-Side Signing
# This configuration enables client-side signing mode where clients must
# sign transactions before submission.

access_key = "test-access-key"
secret_key = "test-secret-key"
bind_address = "127.0.0.1:9200"
region = "us-east-1"
enable_tls = false
walrus_config_path = "client_config.yaml"
request_timeout = 300
max_body_size = 67108864  # 64MB
enable_cors = true

# Client-side signing configuration
[client_signing]
require_signatures = true
validate_signatures = true
sui_rpc_url = "https://fullnode.testnet.sui.io:443"

# Walrus configuration
[walrus]
publisher_url = "https://publisher.walrus-testnet.walrus.space"
aggregator_url = "https://aggregator.walrus-testnet.walrus.space"

# Client credentials
[client_credentials]
"test-access-key" = { sui_address = "0x0000000000000000000000000000000000000000000000000000000000000000", permissions = ["read", "write"], description = "Test credential", active = true }
