# Walrus S3 Gateway Configuration for Client-Side Signing
# This configuration enables client-side signing mode where clients must
# sign transactions before submission.

listen_address = "127.0.0.1:9200"

# Client-side signing configuration
[client_signing]
require_signatures = true
sui_rpc_url = "https://fullnode.testnet.sui.io:443"

# Walrus configuration
[walrus]
publisher_url = "https://publisher.walrus-testnet.walrus.space"
aggregator_url = "https://aggregator.walrus-testnet.walrus.space"

# AWS S3 compatibility mode
[aws]
access_key_id = ""
secret_access_key = ""
region = "us-east-1"

# Metadata storage (file-based for testing)
[metadata]
storage_type = "file"
storage_path = "./s3_metadata"

# Logging configuration
[logging]
level = "info"
