[package]
name = "walrus-move-client"
publish = false
authors = { workspace = true }
version = { workspace = true }
edition = { workspace = true }
license = { workspace = true }

[dependencies]
anyhow = "1.0.80"
futures = "0.3.30"
move_core_types = { workspace = true }
serde_json = "1.0.114"
sui-sdk = { workspace = true }
sui_types = { workspace = true }
tokio = "1.36.0"
tracing = "0.1.40"
walrus-core = { workspace = true }
walrus-service = { workspace = true }

[lints]
workspace = true

[dev-dependencies]
test-cluster = { workspace = true }
walrus-e2e-tests = { path = "../walrus-e2e-tests" }
walrus-test-utils = { workspace = true }
