[package]
name = "walrus-sui"
publish = false
authors = { workspace = true }
version = { workspace = true }
edition = { workspace = true }
license = { workspace = true }

[features]
default = ["test-utils"]
test-utils = []

[dependencies]
anyhow = "1.0.80"
bcs = { workspace = true }
fastcrypto = { workspace = true }
move-core-types = { workspace = true }
serde = { workspace = true }
serde_json = "1.0.115"
sui-move-build = { workspace = true }
sui-sdk = { workspace = true }
sui-types = { workspace = true }
thiserror = { workspace = true }
tokio = { workspace = true, features = ["sync"] }
tokio-stream = { workspace = true }
tracing = "0.1.40"
walrus-core = { workspace = true }

[lints]
workspace = true

[dev-dependencies]
test-cluster = { workspace = true }
tracing-subscriber = "0.3.18"
