name: Test coverage
description: Run all tests and report coverage

runs:
  using: "composite"
  steps:
    - run: cargo install --locked cargo-tarpaulin@0.31.2
      shell: bash

    - name: Run tests (including integration E2E tests) and record coverage
      run: cargo tarpaulin
      shell: bash

    - name: Upload coverage report
      uses: actions/upload-artifact@v4
      with:
        name: Coverage report
        path: tarpaulin-report.html
    - name: Code-coverage report
      uses: irongut/CodeCoverageSummary@v1.3.0
      with:
        filename: cobertura.xml
        badge: true
        fail_below_min: false
        format: markdown
        hide_branch_rate: false
        hide_complexity: true
        indicators: true
        output: both
        thresholds: '50 75'
