[package]
name = "walrus-indexer"
version = "0.1.0"
edition = "2021"
authors = ["Walrus Foundation"]
license = "Apache-2.0"

[[bin]]
name = "walrus-indexer"
path = "src/bin/indexer.rs"

[lib]
name = "walrus_indexer"
path = "src/lib.rs"

[dependencies]
anyhow = { workspace = true }
axum = { workspace = true }
chrono = { workspace = true }
clap = { workspace = true }
hex = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
serde_with = { workspace = true }
tokio = { workspace = true }
tokio-util = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }
typed-store = { workspace = true }

# Walrus dependencies
checkpoint-downloader = { workspace = true }
walrus-core = { path = "../walrus-core" }
walrus-sui = { path = "../walrus-sui" }
walrus-utils = { path = "../walrus-utils" }

# Sui dependencies
move-core-types = { workspace = true }
sui-package-resolver = { workspace = true }
sui-sdk = { workspace = true }
sui-types = { workspace = true }

# Database
rocksdb = { workspace = true }

# Additional dependencies for event processing
bincode = { workspace = true }
futures = { workspace = true }
mysten-metrics = { workspace = true }
prometheus = { workspace = true }

[dev-dependencies]
tempfile = { workspace = true }
tokio = { workspace = true, features = ["macros", "rt"] }
