[package]
name = "walrus-stress"
version.workspace = true
authors.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
anyhow.workspace = true
clap.workspace = true
futures.workspace = true
mysten-metrics.workspace = true
prometheus.workspace = true
rand.workspace = true
serde.workspace = true
sui-sdk.workspace = true
tokio.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true
walrus-core.workspace = true
walrus-service.workspace = true
walrus-sui.workspace = true
walrus-test-utils.workspace = true

[lints]
workspace = true
