version: "3"

services:
  sui-localnet:
    networks:
      testbed-network:
    image: mysten/sui-tools:testnet-v1.35.1
    command:
      [
        "sui",
        "start",
        "--with-faucet",
        # "--force-regenesis", # comment out to use existing genesis
      ]
    healthcheck:
      test: ["CMD", "bash", "-c", "echo > /dev/tcp/127.0.0.1/9000"]
      interval: 5s
      timeout: 10s
      retries: 5
    volumes:
      - sui-config:/root/.sui/sui_config

  walrus-deploy:
    restart: no
    depends_on:
      sui-localnet:
        condition: service_healthy
    networks:
      testbed-network:
    image: mysten/walrus-service:f600f7595744d87072af9c49e2c25ef49d9e268a
    platform: linux/amd64
    hostname: walrus-deploy
    container_name: walrus-deploy
    volumes:
      - walrus-config:/opt/walrus/config
    command: >
      /bin/sh -c "apt install -y git \
      && git clone https://github.com/MystenLabs/walrus-docs \
      && cp -r walrus-docs/contracts /opt/walrus/contracts \
      && cd /opt/walrus && /opt/walrus/bin/walrus-deploy deploy-system-contract \
      --working-dir /opt/walrus \
      --sui-network 'http://sui-localnet:9000;http://sui-localnet:9123/gas' \
      --n-shards 10 \
      --host-addresses 10.0.0.11 10.0.0.12 10.0.0.13 10.0.0.14 \
      --storage-price 5 \
      --write-price 1 \
      --epoch-duration 1h"

  # walrus-node1:
  #   depends_on:
  #     walrus-deploy:
  #       condition: service_completed_successfully
  #   networks:
  #     testbed-network:
  #       ipv4_address: 10.0.0.11
  #   image: mysten/walrus-service:f600f7595744d87072af9c49e2c25ef49d9e268a
  #   platform: linux/amd64
  #   hostname: walrus-node1
  #   container_name: walrus-node1
  #   volumes:
  #     - ./walrus-genesis/static/walrus-node.yaml:/opt/walrus/config/walrus-node.yaml:ro
  #     - ./walrus-genesis/static/sui-config.yaml:/opt/walrus/config/sui-config.yaml:ro
  #     - /tmp/walrus-testbed/walrus/db:/opt/walrus/db:rw
  #   command:
  #     [
  #       "/usr/local/bin/sui-node",
  #       "--config-path",
  #       "/opt/sui/config/fullnode.yaml",
  #     ]
  #   restart: on-failure
  #   logging:
  #     driver: "json-file"
  #     options:
  #       max-file: "10"
  #       max-size: "1g"

volumes:
  sui-config:
  walrus-config:

networks:
  testbed-network:
    driver: bridge
    ipam:
      config:
      - subnet: 10.0.0.0/24
