[package]
name = "walrus-sdk"
publish = false
authors = { workspace = true }
version = { workspace = true }
edition = { workspace = true }
license = { workspace = true }

[features]
service = ["dep:tower-service"]

[dependencies]
bcs.workspace = true
mime = "0.3.17"
reqwest = { workspace = true, features = ["json"] }
serde.workspace = true
serde_json = "1.0.117"
thiserror.workspace = true
tokio.workspace = true
tower-service = { version = "0.3.2", optional = true }
tracing = "0.1.40"
walrus-core.workspace = true

[dev-dependencies]
walrus-core = { workspace = true, features = ["test-utils"] }
walrus-test-utils.workspace = true

[lints]
workspace = true

[package.metadata.docs.rs]
all-features = true
