[package]
name = "walrus-sdk"
publish = false
authors = { workspace = true }
version = { workspace = true }
edition = { workspace = true }
license = { workspace = true }

[dependencies]
bcs.workspace = true
fastcrypto.workspace = true
mime.workspace = true
opentelemetry.workspace = true
p256.workspace = true
rand.workspace = true
reqwest.workspace = true
rustls.workspace = true
rustls-native-certs = "0.7.2"
serde.workspace = true
sui-types.workspace = true
thiserror.workspace = true
tokio.workspace = true
tracing.workspace = true
tracing-opentelemetry.workspace = true
utoipa.workspace = true
walrus-core.workspace = true
x509-cert = "0.2.5"

[dev-dependencies]
axum.workspace = true
axum-server = { workspace = true }
rcgen.workspace = true
walrus-core = { workspace = true, features = ["test-utils"] }
walrus-test-utils.workspace = true

[lints]
workspace = true

[package.metadata.docs.rs]
all-features = true

[target.'cfg(msim)'.dependencies]
sui-simulator.workspace = true
