[package]
name = "walrus-sdk"
publish = false
authors = { workspace = true }
version = { workspace = true }
edition = { workspace = true }
license = { workspace = true }

[dependencies]
bcs.workspace = true
fastcrypto.workspace = true
futures.workspace = true
mime.workspace = true
opentelemetry.workspace = true
reqwest.workspace = true
serde.workspace = true
serde_json.workspace = true
sui-types.workspace = true
thiserror.workspace = true
tokio.workspace = true
tracing.workspace = true
tracing-opentelemetry.workspace = true
utoipa.workspace = true
walrus-core.workspace = true

[dev-dependencies]
walrus-core = { workspace = true, features = ["test-utils"] }
walrus-test-utils.workspace = true

[lints]
workspace = true

[package.metadata.docs.rs]
all-features = true

[target.'cfg(msim)'.dependencies]
sui-simulator.workspace = true
