name: Detect Changes
description: Defines variables indicating the parts of the code that changed
outputs:
  isMove:
    description: True when changes happened in Move code or related build/test files
    value: "${{ steps.diff.outputs.isMove }}"
  isRust:
    description: True when changes happened in Rust code or related build/test files
    value: "${{ steps.diff.outputs.isRust }}"
  isReleaseNotesEligible:
    description: True when changes happened in paths eligible for release notes
    value: "${{ steps.diff.outputs.isReleaseNotesEligible }}"
  isReleaseNotesScript:
    description: True when changes happened in release notes scripts
    value: "${{ steps.diff.outputs.isReleaseNotesScript }}"
  isDenyConfig:
    description: True when changes happened in the configuration for `cargo-deny`
    value: "${{ steps.diff.outputs.isDenyConfig }}"
  isTestConfig:
    description: True when changes happened in the configuration for `nextest`
    value: "${{ steps.diff.outputs.isTestConfig }}"
  isTestnetContracts:
    description: True when changes happened in the `testnet-contracts` directory
    value: "${{ steps.diff.outputs.isTestnetContracts }}"
  isMainnetContracts:
    description: True when changes happened in the `mainnet-contracts` directory
    value: "${{ steps.diff.outputs.isMainnetContracts }}"
  isDevelopmentContracts:
    description: True when changes happened in the `contracts` directory
    value: "${{ steps.diff.outputs.isDevelopmentContracts }}"
  isExampleConfig:
    description: True when changes happened in the example config files
    value: "${{ steps.diff.outputs.isExampleConfig }}"
  isOpenapi:
    description: True when changes happened in the OpenAPI files
    value: "${{ steps.diff.outputs.isOpenapi }}"
  isCLI:
    description: True when changes happened in the files directly affecting the Walrus CLI
    value: "${{ steps.diff.outputs.isCLI }}"

runs:
  using: composite
  steps:
    - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # pin@v6.0.1
    - name: Detect Changes
      uses: dorny/paths-filter@de90cc6fb38fc0963ad72b210f1f284cd68cea36 # pin@v3.0.2
      id: diff
      with:
        filters: |
          isMove:
            - 'contracts/**'
            - 'scripts/move_tests.sh'
            - '.github/workflows/code.yml'
          isRust:
            - 'crates/**'
            - 'Cargo.toml'
            - 'Cargo.lock'
            - 'rust-toolchain.toml'
            - '.github/workflows/code.yml'
            - 'setup/*.yaml'
          isReleaseNotesEligible:
            - 'contracts/**'
            - 'crates/**'
            - 'docker/**'
            - 'docs/**'
          isReleaseNotesScript:
            - 'scripts/release_notes.py'
            - 'scripts/release_notes_test.py'
          isDenyConfig:
            - 'deny.toml'
          isTestConfig:
            - '.config/nextest.toml'
          isTestnetContracts:
            - 'testnet-contracts/**'
          isMainnetContracts:
            - 'mainnet-contracts/**'
          isDevelopmentContracts:
            - 'contracts/**'
          isExampleConfig:
            - 'crates/walrus-service/node_config_example.yaml'
            - 'crates/walrus-sdk/client_config_example.yaml'
            - 'crates/walrus-upload-relay/walrus_upload_relay_config_example.yaml'
          isOpenapi:
            - 'crates/walrus-service/*_openapi.html'
            - 'crates/walrus-service/*_openapi.yaml'
            - 'crates/walrus-upload-relay/upload_relay_openapi.html'
            - 'crates/walrus-upload-relay/upload_relay_openapi.yaml'
          isCLI:
            - 'crates/walrus-service/bin/client.rs'
            - 'crates/walrus-service/src/client/cli.rs'
            - 'crates/walrus-service/src/client/cli/**'
