name: Detect Changes
description: Defines variables indicating the parts of the code that changed
outputs:
  isMove:
    description: True when changes happened in Move code or related build/test files
    value: "${{ steps.diff.outputs.isMove }}"
  isRust:
    description: True when changes happened in Rust code or related build/test files
    value: "${{ steps.diff.outputs.isRust }}"
  isReleaseNotesEligible:
    description: True when changes happened in paths eligible for release notes
    value: "${{ steps.diff.outputs.isReleaseNotesEligible }}"
  isDenyConfig:
    description: True when changes happened in the configuration for `cargo-deny`
    value: "${{ steps.diff.outputs.isDenyConfig }}"
  isTestConfig:
    description: True when changes happened in the configuration for `nextest`
    value: "${{ steps.diff.outputs.isTestConfig }}"
  isTestnetContracts:
    description: True when changes happened in the `testnet-contracts` directory
    value: "${{ steps.diff.outputs.isTestnetContracts }}"
  isMainnetContracts:
    description: True when changes happened in the `contracts` directory
    value: "${{ steps.diff.outputs.isMainnetContracts }}"
  isExampleConfig:
    description: True when changes happened in the example config files
    value: "${{ steps.diff.outputs.isExampleConfig }}"
  isOpenapi:
    description: True when changes happened in the OpenAPI files
    value: "${{ steps.diff.outputs.isOpenapi }}"

runs:
  using: composite
  steps:
    - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # pin@v4
    - name: Detect Changes
      uses: dorny/paths-filter@v3
      id: diff
      with:
        filters: |
          isMove:
            - 'contracts/**'
            - 'scripts/move_coverage.sh'
            - '.github/workflows/code.yml'
          isRust:
            - 'crates/**'
            - 'Cargo.toml'
            - 'Cargo.lock'
            - 'rust-toolchain.toml'
            - '.github/workflows/code.yml'
          isReleaseNotesEligible:
            - 'contracts/**'
            - 'crates/**'
            - 'docker/**'
            - 'docs/**'
          isDenyConfig:
            - 'deny.toml'
          isTestConfig:
            - '.config/nextest.toml'
          isTestnetContracts:
            - 'testnet-contracts/**'
          isMainnetContracts:
            - 'contracts/**'
          isExampleConfig:
            - 'crates/walrus-service/node_config_example.yaml'
            - 'crates/walrus-sdk/client_config_example.yaml'
          isOpenapi:
            - 'crates/walrus-service/*_openapi.html'
            - 'crates/walrus-service/*_openapi.yaml'
