[package]
name = "walrus-service"
publish = false
authors = { workspace = true }
version = { workspace = true }
edition = { workspace = true }
license = { workspace = true }

[dependencies]
anyhow = "1.0.80"
bcs = { workspace = true }
clap = { version = "4.5", features = ["derive"] }
fastcrypto = { workspace = true }
prometheus = "0.13.3"
rocksdb = "0.21"
serde = { version = "1.0.197", features = ["derive"] }
thiserror = { workspace = true }
tokio = { version = "1.36.0", features = ["rt-multi-thread", "macros"] }
tokio-stream = "0.1.14"
typed-store = { workspace = true }
walrus-core = { workspace = true }

[lints]
workspace = true

[[bin]]
name = "client"
path = "bin/client.rs"

[dev-dependencies]
rand = "0.8.5"
tempfile = { workspace = true }
walrus-test-utils = { workspace = true }
