[package]
name = "walrus-service"
publish = false
authors.workspace = true
version.workspace = true
edition.workspace = true
license.workspace = true

[features]
default = ["test-utils"]
test-utils = ["dep:tempfile", "dep:walrus-test-utils", "walrus-core/test-utils"]

[dependencies]
anyhow.workspace = true
async-trait = "0.1.80"
axum = { version = "0.7.5", features = ["http2"] }
bcs.workspace = true
clap = { workspace = true, features = ["string"] }
colored = "2.1.0"
fastcrypto.workspace = true
futures.workspace = true
git-version = "0.3.9"
home = "0.5.9"
humantime = "2.1.0"
indoc = "2.0.5"
mime.workspace = true
mysten-metrics.workspace = true
opentelemetry = "^0.23.0"
opentelemetry-otlp = "^0.16"
opentelemetry-stdout = { version = "^0.4.0", features = ["trace"] }
opentelemetry_sdk = { version = "^0.23.0", features = ["trace", "rt-tokio", "rt-tokio-current-thread"] }
pin-project = "1.1.5"
prettytable = "0.10.0"
prometheus.workspace = true
rand.workspace = true
regex = "1"
reqwest.workspace = true
rocksdb = "0.21.0"
serde.workspace = true
serde_json.workspace = true
serde_with.workspace = true
serde_yaml.workspace = true
sui-sdk.workspace = true
sui-types.workspace = true
telemetry-subscribers.workspace = true
tempfile = { workspace = true, optional = true }
thiserror.workspace = true
tokio = { workspace = true, features = ["rt-multi-thread", "macros"] }
tokio-stream.workspace = true
tokio-util = "0.7.10"
tower-http = { version = "0.5.2", features = ["trace"] }
tracing.workspace = true
tracing-opentelemetry = "0.24"
tracing-subscriber.workspace = true
typed-store.workspace = true
utoipa = { workspace = true, features = ["axum_extras"] }
utoipa-redoc = { version = "4.0.0", features = ["axum"] }
walrus-core = { workspace = true, features = ["utoipa"] }
walrus-sdk.workspace = true
walrus-sui.workspace = true
walrus-test-utils = { workspace = true, optional = true }

[lints]
workspace = true

[[bin]]
name = "walrus"
path = "bin/client.rs"

[[bin]]
name = "walrus-node"
path = "bin/node.rs"

[dev-dependencies]
mockall = "0.12.1"
rand.workspace = true
tempfile.workspace = true
walrus-core = { workspace = true, features = ["test-utils"] }
walrus-test-utils.workspace = true
