# Example configuration for the storage client.
#
# Default optional values are commented out.

system_object: 0xd6f0cacdb8b365cdda24ab954a32ebc86f8b8a1707322b4cc0ba54dcbbbc5772
# wallet_config: null
# communication_config:
#   max_concurrent_writes: null
#   max_concurrent_sliver_reads: null
#   max_concurrent_metadata_reads: null
#   max_concurrent_status_reads: null
#   max_data_in_flight: null
#   reqwest_config:
#     total_timeout:
#       secs: 180
#       nanos: 0
#     pool_idle_timeout: null
#     http2_keep_alive_timeout:
#       secs: 5
#       nanos: 0
#     http2_keep_alive_interval:
#       secs: 30
#       nanos: 0
#     http2_keep_alive_while_idle: true
#   request_rate_config:
#     max_node_connections: 10
#     max_retries: 5
#     min_backoff:
#       secs: 2
#       nanos: 0
#     max_backoff:
#       secs: 60
#       nanos: 0
