# Example configuration for a Walrus storage node.
#
# Only the uncommented parameters are required.
# Default optional values are commented out.

storage_path: /path/to/node/storage
protocol_key_pair: /path/to/keypair
network_key_pair: /path/to/network_keypair
sui:
  rpc: https://fullnode.testnet.sui.io:443
  system_object: 0xd6f0cacdb8b365cdda24ab954a32ebc86f8b8a1707322b4cc0ba54dcbbbc5772
  wallet_config: /path/to/sui/wallet-config.yaml
  # event_polling_interval_millis: 400
  # gas_budget: 500000000
# metrics_address: 0.0.0.0:9184
# rest_api_address: 0.0.0.0:9185
# blob_recovery:
#   max_concurrent_blob_syncs: 10
#   retry_interval_min_secs: 1
#   retry_interval_max_secs: 3600
#   metadata_request_timeout_secs: 5
#   max_concurrent_metadata_requests: 1
#   sliver_request_timeout_secs: 300
#   invalidity_sync_timeout_secs: 300
# db_config:
#   metadata:
#     enable_blob_files: true
#     min_blob_size: 1048576
#     blob_file_size: 268435456
#     blob_compression_type: zstd
#     enable_blob_garbage_collection: true
#     blob_garbage_collection_age_cutoff: 0.5
#     blob_garbage_collection_force_threshold: 0.5
#     blob_compaction_read_ahead_size: 10485760
#     write_buffer_size: 268435456
#     target_file_size_base: 4194304
#     max_bytes_for_level_base: 33554432
#   blob_info:
#     enable_blob_files: false
#     min_blob_size: 0
#     blob_file_size: 0
#     blob_compression_type: none
#     enable_blob_garbage_collection: false
#     blob_garbage_collection_age_cutoff: 0.0
#     blob_garbage_collection_force_threshold: 0.0
#     blob_compaction_read_ahead_size: 0
#     write_buffer_size: 67108864
#     target_file_size_base: 67108864
#     max_bytes_for_level_base: 536870912
#   event_cursor:
#     enable_blob_files: false
#     min_blob_size: 0
#     blob_file_size: 0
#     blob_compression_type: none
#     enable_blob_garbage_collection: false
#     blob_garbage_collection_age_cutoff: 0.0
#     blob_garbage_collection_force_threshold: 0.0
#     blob_compaction_read_ahead_size: 0
#     write_buffer_size: 67108864
#     target_file_size_base: 67108864
#     max_bytes_for_level_base: 536870912
#   shard:
#     enable_blob_files: true
#     min_blob_size: 1048576
#     blob_file_size: 268435456
#     blob_compression_type: zstd
#     enable_blob_garbage_collection: true
#     blob_garbage_collection_age_cutoff: 0.5
#     blob_garbage_collection_force_threshold: 0.5
#     blob_compaction_read_ahead_size: 10485760
#     write_buffer_size: 268435456
#     target_file_size_base: 4194304
#     max_bytes_for_level_base: 33554432
