[package]
name = "walrus-core"
publish = false
authors = { workspace = true }
version = { workspace = true }
edition = { workspace = true }
license = { workspace = true }

[dependencies]
bcs = { workspace = true }
fastcrypto = { workspace = true }
# TODO(mlegner): Update as soon as there is an official release with the ESI fix.
raptorq = { git = "https://github.com/cberner/raptorq", rev = "da79ac2ba51e99484c81901fe293a2d8b32add49" }
serde = { workspace = true }
thiserror = { workspace = true }

[lints]
workspace = true

[dev-dependencies]
rand = { workspace = true }
walrus-test-utils = { workspace = true }
