# See https://nexte.st/docs/configuration/ for configuration parameters.

[profile.default]
fail-fast = false # do not stop at first failure
slow-timeout = { period = "1m", terminate-after = 5 }

[[profile.default.overrides]]
filter = 'package(walrus-e2e-tests)'
threads-required = 4

[profile.ci]
retries = 2 # retry twice for a total of 3 attempts
slow-timeout = { period = "1m", terminate-after = 10 } # Timeout tests after 10 minutes

[[profile.ci.overrides]]
filter = 'package(walrus-e2e-tests) or package(walrus-sui) or test(nodes_drive_epoch_change)'
slow-timeout = { period = "2m", terminate-after = 5 } # Mark E2E tests as slow only after 2 minutes
threads-required = 4

[profile.simtest]
slow-timeout = { period = "5m", terminate-after = 6 } # Timeout tests after 30 minutes
test-threads = "num-cpus"
