[package]
name = "walrus-utils"
version.workspace = true
authors.workspace = true
edition.workspace = true
license.workspace = true

[features]
backoff = ["dep:rand", "dep:serde_with", "tokio/time"]
config = ["dep:home"]
default = []
http = ["dep:bytes", "dep:http-body", "dep:pin-project"]
log = ["dep:humantime", "dep:once_cell"]
metrics = ["dep:once_cell", "dep:prometheus", "dep:tap", "dep:thiserror"]
test-utils = ["dep:tempfile", "tokio/sync"]
tokio-metrics = ["dep:tokio-metrics"]

[dependencies]
anyhow.workspace = true
bytes = { workspace = true, optional = true }
const-str.workspace = true
git-version.workspace = true
home = { workspace = true, optional = true }
http-body = { version = "1", optional = true }
humantime = { workspace = true, optional = true }
once_cell = { workspace = true, optional = true }
pin-project = { workspace = true, optional = true }
prometheus = { workspace = true, optional = true }
rand = { workspace = true, optional = true }
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true, optional = true }
serde_with = { workspace = true, optional = true }
serde_yaml = { workspace = true }
tap = { workspace = true, optional = true }
tempfile = { workspace = true, optional = true }
thiserror = { workspace = true, optional = true }
tokio = { workspace = true, features = ["macros", "rt-multi-thread"], optional = true }
tokio-metrics = { workspace = true, optional = true }
tokio-util = { workspace = true, optional = true }
tracing.workspace = true
tracing-subscriber = { workspace = true, optional = true }

[lints]
workspace = true

[dev-dependencies]
http-body-util.workspace = true
tempfile.workspace = true
tokio = { workspace = true, features = ["test-util"] }
tracing-subscriber.workspace = true
walrus-test-utils.workspace = true
