[package]
name = "walrus-e2e-tests"
publish = false
authors = { workspace = true }
edition = { workspace = true }
license = { workspace = true }
version = { workspace = true }

[dependencies]
anyhow = "1.0.80"
sui-move-build = { workspace = true }
sui-sdk = { workspace = true }
tokio = { version = "1.36.0", features = ["macros"] }

[dev-dependencies]
test-cluster = { workspace = true }
