name: Create Walrus Release
run-name: Create Walrus Release for ${{ inputs.release_tag }}

concurrency: ${{ github.workflow }}-${{ inputs.release_tag }}

on:
  workflow_dispatch:
    inputs:
      release_tag:
        description: 'Sui Release Tag'
        type: string
        required: true
      previous_branch:
        description: 'Previous Release branch or commit hash'
        type: string
        required: true
      current_branch:
        description: 'Current Release branch or commit hash'
        type: string
        required: true

env:
  RELEASE_NOTES_FILE: "./release_notes.txt"

jobs:
  get-release-notes:
    name: Get Release Notes for ${{ inputs.release_tag }} release
    runs-on: ubuntu-latest

    steps:
      - name: Get commits for branches
        shell: bash
        working-directory: ./
        run: |
          echo "previous_commit=$(curl -s \
            -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            https://api.github.com/repos/MystenLabs/walrus/commits/${{ inputs.previous_branch }}| jq .sha | tr -d '"')" >> $GITHUB_ENV
          echo "current_commit=$(curl -s \
            -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            https://api.github.com/repos/MystenLabs/walrus/commits/${{ inputs.current_branch }} | jq .sha | tr -d '"')" >> $GITHUB_ENV

      - name: Checkout main
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # pin@v4
        with:
          fetch-depth: 0
          ref: main

      - name: Setup Python
        uses: actions/setup-python@8d9ed9ac5c53483de85588cdf95a591a75ab9f55 # pin@v5.5.0
        with:
          python-version: 3.10.10

      - name: Generate Release Notes
        shell: bash
        working-directory: ./
        run: |
          WALRUS_REPO_TOKEN=${{ secrets.GITHUB_TOKEN }} \
          python ./scripts/release_notes.py generate ${{ env.previous_commit }} ${{ env.current_commit }} | tee -a ${{ env.RELEASE_NOTES_FILE }}
          echo "---" >> ${{ env.RELEASE_NOTES_FILE }}
          echo "#### Full Log: https://github.com/MystenLabs/walrus/commits/${{ inputs.release_tag }}" >> ${{ env.RELEASE_NOTES_FILE }}

          if [[ ${{ inputs.release_tag }} == devnet* ]]; then
            echo "pre_release=true" >> $GITHUB_ENV
          else
            echo "pre_release=false" >> $GITHUB_ENV
          fi

      - name: Create Release
        uses: actions/create-release@0cb9c9b65d5d1901c1f53e5e66eaf4afd303e70e # pin@v1
        env:
          GITHUB_TOKEN: ${{ secrets.WALRUS_CREATE_RELEASE }}
        with:
          tag_name: ${{ inputs.release_tag }}
          release_name: ${{ inputs.release_tag }}
          body_path: ${{ env.RELEASE_NOTES_FILE }}
          draft: false
          prerelease: ${{ env.pre_release }}
