name: Tag Walrus Branch

on:
  repository_dispatch:
    types: [tag-walrus-branch]

  workflow_call:
    inputs:
      walrus_commit:
        description: 'Walrus repo commit to tag'
        type: string
        required: true
      tag_name:
        description: 'Tag Name'
        type: string
        required: true
  workflow_dispatch:
    inputs:
      walrus_commit:
        description: 'Walrus repo commit to tag'
        type: string
        required: true
      tag_name:
        description: 'Tag Name'
        type: string
        required: true

env:
  WALRUS_COMMIT: "${{ github.event.client_payload.walrus_commit || inputs.walrus_commit }}"
  TAG_NAME: "${{ github.event.client_payload.tag_name || inputs.tag_name }}"

jobs:
  tag:
    name: Tag
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # pin@v4

      - name: Tag
        uses: julbme/gh-action-manage-tag@8daf6387badea2c6b8f989bd0f82b5a9ef1d84e6 # pin@v1
        with:
          name: ${{ env.TAG_NAME }}
          state: present
          from: ${{ env.WALRUS_COMMIT }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
