name: Update bin.wal.app with latest binaries

on:
  repository_dispatch:
    types: [update-sites-bins]
  # every week
  schedule:
    - cron: "14 3 * * 0"
  # on demand
  workflow_dispatch:

concurrency: ci-${{ github.ref }}

permissions:
  contents: read

jobs:
  # We store the data for the Sui wallet and the site object in GitHub variables
  # (https://github.com/MystenLabs/walrus/settings/variables/actions) and secrets
  # (https://github.com/MystenLabs/walrus/settings/secrets/actions).
  update-bin-walrus-site:
    name: Update Walrus Site bin.wal.app
    runs-on: ubuntu-ghcloud
    env:
      # Colors don't seem to work properly with the multiline commands.
      NO_COLOR: 1
      RUST_LOG: info
      EPOCHS: 10
      BUILD_DIR: site
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # pin@v4
      - uses: ./.github/actions/set-up-walrus
        with:
          SUI_ADDRESS: "${{ vars.SUI_ADDRESS }}"
          SUI_KEYSTORE: "${{ secrets.SUI_KEYSTORE }}"
          WALRUS_CONFIG: "${{ vars.WALRUS_CONFIG }}"
          SUI_NETWORK: mainnet

      - name: Create temporary directory
        run: "mkdir -p ${{ env.BUILD_DIR }}"
      - name: Download latest mainnet and testnet binaries
        run: |
          for arch in ubuntu-x86_64 ubuntu-x86_64-generic macos-x86_64 macos-arm64 windows-x86_64.exe; do
          for env in mainnet testnet; do
          name=walrus-$env-latest-$arch
          curl https://storage.googleapis.com/mysten-walrus-binaries/$name -o ${{ env.BUILD_DIR }}/$name
          done
          done

      # TODO: Remove this step once the site-builder supports supports storing multiple blobs
      # simultaneously.
      - name: Store blobs on Walrus
        run: walrus store ${{ env.BUILD_DIR }}/* --epochs ${{ env.EPOCHS }}

      - name: Update Walrus Site
        run: >
          site-builder
          update --list-directory ${{ env.BUILD_DIR }} ${{ vars.WALRUS_SITE_OBJECT_BIN }}
          --epochs ${{ env.EPOCHS }}
          --permanent
          --force
